apiVersion: v2
name: grafana
description: A Grafana Helm chart for Kubernetes
version: 1.0.0
appVersion: latest
adminUser: admin
adminPassword: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true






